# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
